version: '3'

services: 
    app:
        build: ./frontend
        entrypoint: ./.docker/entrypoint.sh
        container_name: desafio-frontend
        ports: 
            - 3001:3000
        volumes: 
            - ./frontend:/home/node/app

    backend:
        build: ./backend
        entrypoint: ./.docker/entrypoint.sh
        container_name: desafio-backend
        ports: 
            - 3000:3000
        volumes: 
            - ./backend:/home/node/app
